# syntax=docker/dockerfile:1
FROM node:18.19.0-alpine3.19 as base

ENV NEXT_PUBLIC_INFURA_KEY=e8af468a5c504d7c95dee04787675100

RUN mkdir /app
WORKDIR /app

COPY . .
RUN yarn && yarn build

ENTRYPOINT ["yarn", "workspace", "arb-token-bridge-ui", "start", "-H", "0.0.0.0"]